apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: product-service
  name: product-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - image: dhavalmodi11/product-service:1.0.0
        imagePullPolicy: IfNotPresent
        name: product-service      
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-service
  name: product-service
  namespace: default
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: product-service
  sessionAffinity: None
  type: LoadBalancer