apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: customer-service
  name: customer-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - image: dhavalmodi11/customer-service:1.0.0
        imagePullPolicy: IfNotPresent
        name: customer-service    
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-service
  name: customer-service
  namespace: default
spec:
  ports:
  - port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: customer-service
  sessionAffinity: None
  type: LoadBalancer